### ISSUE TITLE
Some documentation for starters

### ISSUE THREAD

**Issue by imranakram** [EricHerlitz/Mobile-BankId-.NET-Example#1]
Hi,

The app needs some basic settings to be done to run properly. Could you please add some documentation for guiding users on how to setup this application to use for the first time.

Thanks,
Imran

**Comment by EricHerlitz** [comment]
I will post a blog on this project in April describing the entire setup. Until then the official documentation on using the BankID-services are available here https://www.bankid.com/bankid-i-dina-tjanster/rp-info

**Comment by imranakram** [comment]
Thanks :)

**Comment by DanielCornelius** [comment]
I had issues with using customHttpBinding in app.config. 
Got TLS/SSL error from service.
Changed to basicHttpBinding and it worked.
Just wanted you to know.
Thanx!
//Daniel

**Comment by KimKarlsson** [comment]
@EricHerlitz could you post a link to that blog post you were mentioning, about the setup?

**Comment by AndersBillLinden** [comment]
Thanks for the fantastic documentation!
I am almost there!

I need some final help, if you are not the right person to ask (maybe you are a volunteer?), let me know.

I am getting a SecurityNegotiationException when I try to use this code in a desktop application (winforms):
````
private void button1_Click(object sender, EventArgs e)
{
  var client = new RpServicePortTypeClient();

  var request = new SignRequestType
  {
    personalNumber = txtPersonalNumber.Text,
    userVisibleData = txtMessage.Text
  };

  var response = client.Sign(request);
}
````

The error is 
````
An unhandled exception of type 'System.ServiceModel.Security.SecurityNegotiationException' occurred in mscorlib.dll

Additional information: Could not establish secure channel for SSL/TLS with authority 'appapi2.test.bankid.com'.
````

having a Web.config that looks like
````
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
    <system.serviceModel>
        <bindings>
            <customBinding>
                <binding name="RpServiceSoapBinding">
                    <textMessageEncoding messageVersion="Soap11" />
                    <httpsTransport requireClientCertificate="true" />
                </binding>
            </customBinding>
        </bindings>
        <client>
            <endpoint address="https://appapi2.test.bankid.com/rp/v4"
                binding="customBinding"
                bindingConfiguration="RpServiceSoapBinding"
                contract="BankIDService.RpServicePortType"
                name="RpServiceSoapPort"
                behaviorConfiguration="bankid"/>
        </client>
        <behaviors>
            <endpointBehaviors>
                <behavior name="bankid">
                    <clientCredentials>
                        <clientCertificate findValue="FP Testcert 2"
                            x509FindType="FindBySubjectName"
                            storeLocation="LocalMachine"
                            storeName="My" />
                        <serviceCertificate>
                            <defaultCertificate findValue="Test BankID SSL Root CA v1 Test"
                                storeLocation="LocalMachine"
                                storeName="Root"
                                x509FindType="FindBySubjectName"/>
                            <authentication certificateValidationMode="None"
                                revocationMode="NoCheck"
                                trustedStoreLocation="LocalMachine"/>
                        </serviceCertificate>
                    </clientCredentials>
                </behavior>
            </endpointBehaviors>
        </behaviors>
    </system.serviceModel>
</configuration>
````

Both the cer and the pfx are installed by double clicking in explorer, both on LocalMachine, the cer as Trusted Root Certification Authorities, the pfx as Personal.

The bankid_test.cer is fetched from https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v2.15.pdf and is from chapter 7 Test Environment.

It is significantly larger than the one you had in your example, starting with `MIIF0DCCA` and ending with `WJ5vZOP2HsA==`.

**Comment by EricHerlitz** [comment]
The docs are up at http://www.herlitz.nu/2017/09/13/integrating-with-swedish-bankid-and-.net/
