### ISSUE TITLE
Migrating from soap to json?

### ISSUE THREAD

**Issue by AndersBillLinden** [EricHerlitz/Mobile-BankId-.NET-Example#6]
Thanks for the effort putting together this code. Now, this is using soap instead of json and needs to be updated before 2020-02-01 to still have it working. Is there an update?

**Comment by EricHerlitz** [comment]
> Thanks for the effort putting together this code. Now, this is using soap instead of json and needs to be updated before 2020-02-01 to still have it working. Is there an update?

There is, I haven't pushed it to github just yet. A change is that it is written in .net core so a totally new version of this api.

**Comment by EricHerlitz** [comment]
You can find the new repository here https://github.com/EricHerlitz/Swedish-BankID-.NET-Core
I'll be adding some documentation and examples during the coming days
